export const  ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    START_PROCESS: "START_PROCESS",
    ERROR_PROCESS: "ERROR_PROCESS",
    FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS"
}